import os

files = [
    'adani_airports.png', 'adani_infra.png', 'agartala_airport.png', 'ajanta_pharma.png', 'apple.png',
    'ashoka_university.png', 'barc.png', 'becil.png', 'bita_goa.png', 'bits_pilani.png', 'cipla.png',
    'coca_cola.png', 'cognizant.png', 'cult_fitness.png', 'decathlong.png', 'delhi_airport.png', 'divis_lab.png',
    'dlf.png', 'dlf_camelias.png', 'embassy_business_park.png', 'facebook.png', 'gd_goenka_school.png',
    'goa_shipyard.png', 'gold_gym.png', 'honda.png', 'hyatt.png', 'hyundai.png', 'india_tv.png', 'indian_express.png',
    'indigo.png', 'inox.png', 'iocl.png', 'isb.png', 'jagran_tv.png', 'jio.png', 'jmd.png', 'kmpg.png',
    'lemon_tree.png', 'lodha_group.png', 'm3m.png', 'maharaja_agrasen_hospital.png', 'marriot.png', 'maruti.png',
    'max_infra.png', 'max_square.png', 'mercedes.png', 'mumbai_airport.png', 'ndtv.png', 'oberoi.png',
    'oxygen_business_park.png', 'pathways_school.png', 'pepsi_co.png', 'prestige.png', 'pti.png', 'radisson.png',
    'raheja.png', 'reddys.png', 'reliance_infra.png', 'reliance_vantara.png', 'saint_marks_school.png',
    'shapoorji_palonji.png', 'sharda_university.png', 'shereton.png', 'smartworks.png', 'starsports.png',
    'stateman.png', 'stpi.png', 'tata_steel.png', 'the_lodhi.png', 'udaipur_airport.png', 'vatika.png',
    'venkatesh_hospital.png', 'westin_hotels.png', 'wework.png'
]

mapping = {
    'adani_airports.png': ('Adani Airports', 'airports'),
    'adani_infra.png': ('Adani Infra', 'industrial'),
    'agartala_airport.png': ('Agartala Airport', 'airports'),
    'ajanta_pharma.png': ('Ajanta Pharma', 'healthcare'),
    'apple.png': ('Apple', 'corporate'),
    'ashoka_university.png': ('Ashoka University', 'education'),
    'barc.png': ('BARC', 'government'),
    'becil.png': ('BECIL', 'government'),
    'bita_goa.png': ('BITS Pilani Goa', 'education'),
    'bits_pilani.png': ('BITS Pilani', 'education'),
    'cipla.png': ('Cipla', 'healthcare'),
    'coca_cola.png': ('Coca-Cola', 'corporate'),
    'cognizant.png': ('Cognizant', 'corporate'),
    'cult_fitness.png': ('Cult.fit', 'hospitality'),
    'decathlong.png': ('Decathlon', 'hospitality'),
    'delhi_airport.png': ('Delhi Airport', 'airports'),
    'divis_lab.png': ('Divis Laboratories', 'healthcare'),
    'dlf.png': ('DLF', 'real-estate'),
    'dlf_camelias.png': ('DLF The Camellias', 'real-estate'),
    'embassy_business_park.png': ('Embassy Business Park', 'real-estate'),
    'facebook.png': ('Facebook', 'corporate'),
    'gd_goenka_school.png': ('GD Goenka School', 'education'),
    'goa_shipyard.png': ('Goa Shipyard', 'government'),
    'gold_gym.png': ('Gold Gym', 'hospitality'),
    'honda.png': ('Honda', 'corporate'),
    'hyatt.png': ('Hyatt', 'hospitality'),
    'hyundai.png': ('Hyundai', 'corporate'),
    'india_tv.png': ('India TV', 'media'),
    'indian_express.png': ('Indian Express', 'media'),
    'indigo.png': ('IndiGo', 'airports'),
    'inox.png': ('INOX', 'hospitality'),
    'iocl.png': ('IndianOil', 'industrial'),
    'isb.png': ('ISB', 'education'),
    'jagran_tv.png': ('Jagran TV', 'media'),
    'jio.png': ('Reliance Jio', 'media'),
    'jmd.png': ('JMD', 'real-estate'),
    'kmpg.png': ('KPMG', 'finance'),
    'lemon_tree.png': ('Lemon Tree Hotels', 'hospitality'),
    'lodha_group.png': ('Lodha Group', 'real-estate'),
    'm3m.png': ('M3M', 'real-estate'),
    'maharaja_agrasen_hospital.png': ('Maharaja Agrasen Hospital', 'healthcare'),
    'marriot.png': ('Marriott', 'hospitality'),
    'maruti.png': ('Maruti Suzuki', 'corporate'),
    'max_infra.png': ('Max Infra', 'real-estate'),
    'max_square.png': ('Max Square', 'real-estate'),
    'mercedes.png': ('Mercedes-Benz', 'corporate'),
    'mumbai_airport.png': ('Mumbai Airport', 'airports'),
    'ndtv.png': ('NDTV', 'media'),
    'oberoi.png': ('Oberoi Hotels', 'hospitality'),
    'oxygen_business_park.png': ('Oxygen Business Park', 'real-estate'),
    'pathways_school.png': ('Pathways School', 'education'),
    'pepsi_co.png': ('PepsiCo', 'corporate'),
    'prestige.png': ('Prestige Group', 'real-estate'),
    'pti.png': ('PTI', 'media'),
    'radisson.png': ('Radisson', 'hospitality'),
    'raheja.png': ('Raheja Corp', 'real-estate'),
    'reddys.png': ('Dr. Reddys', 'healthcare'),
    'reliance_infra.png': ('Reliance Infra', 'real-estate'),
    'reliance_vantara.png': ('Reliance Vantara', 'corporate'),
    'saint_marks_school.png': ('St. Marks School', 'education'),
    'shapoorji_palonji.png': ('Shapoorji Pallonji', 'real-estate'),
    'sharda_university.png': ('Sharda University', 'education'),
    'shereton.png': ('Sheraton', 'hospitality'),
    'smartworks.png': ('Smartworks', 'real-estate'),
    'starsports.png': ('Star Sports', 'media'),
    'stateman.png': ('The Statesman', 'media'),
    'stpi.png': ('STPI', 'government'),
    'tata_steel.png': ('Tata Steel', 'industrial'),
    'the_lodhi.png': ('The Lodhi', 'hospitality'),
    'udaipur_airport.png': ('Udaipur Airport', 'airports'),
    'vatika.png': ('Vatika Group', 'real-estate'),
    'venkatesh_hospital.png': ('Venkateshwar Hospital', 'healthcare'),
    'westin_hotels.png': ('Westin Hotels', 'hospitality'),
    'wework.png': ('WeWork', 'real-estate')
}

res = []
for f in files:
    name, cat = mapping[f]
    id_name = f.replace('.png', '')
    res.append(f'  {{ id: "{id_name}", name: "{name}", src: "/Clients/new/{f}", category: "{cat}" }},')

with open('new_clients.txt', 'w') as out:
    out.write('\n'.join(res))
